"""Add machine_id to Product, prep for composite key

Revision ID: 0e8df8517d51
Revises: 60d541a76f35
Create Date: 2025-04-14 02:02:25.285689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e8df8517d51'
down_revision = '60d541a76f35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('machine_id', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('product_motor_id_key', type_='unique')
        batch_op.create_index(batch_op.f('ix_product_machine_id'), ['machine_id'], unique=False)
        batch_op.create_unique_constraint('uq_machine_motor_product', ['machine_id', 'motor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint('uq_machine_motor_product', type_='unique')
        batch_op.drop_index(batch_op.f('ix_product_machine_id'))
        batch_op.create_unique_constraint('product_motor_id_key', ['motor_id'])
        batch_op.drop_column('machine_id')

    # ### end Alembic commands ###
