"""empty message

Revision ID: 12cb266fe7fc
Revises: 0e8df8517d51
Create Date: 2025-04-18 18:26:48.811211

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '12cb266fe7fc'
down_revision = '0e8df8517d51'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vend_command', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=sa.VARCHAR(length=30),
               type_=sa.String(length=40),
               existing_nullable=False)
        batch_op.create_index(batch_op.f('ix_vend_command_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_vend_command_vend_id'), ['vend_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vend_command', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_vend_command_vend_id'))
        batch_op.drop_index(batch_op.f('ix_vend_command_status'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=30),
               existing_nullable=False)

    # ### end Alembic commands ###
