"""Initial migration with Product, VendCommand, Transaction models

Revision ID: 690b6f3cbd4f
Revises: 1c009090d99f
Create Date: 2025-04-13 09:58:04.378587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '690b6f3cbd4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('motor_id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('image_url', sa.String(length=255), nullable=True))
        batch_op.alter_column('name',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.String(length=100),
               existing_nullable=False)
        batch_op.create_unique_constraint(None, ['motor_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('name',
               existing_type=sa.String(length=100),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)
        batch_op.drop_column('image_url')
        batch_op.drop_column('motor_id')

    # ### end Alembic commands ###
